apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  type: NodePort
  selector:
    app: mysql
---
apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: mysql
    env: test
spec:
  containers:
  - name: mysql
    image: mysql:5.7
    args:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: password
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: tmp-volume
    ports:
      - containerPort: 3306
        name: mysql
  nodeSelector:
    storage: mysql
  volumes:
    - name: tmp-volume
      hostPath:
        path: /tmp/data
        type: Directory
