apiVersion: v1
kind: Service
metadata:
  name: tsai-service
spec:
  type: NodePort
  ports:
  - port: 3000
    nodePort: 30390
    protocol: TCP
    targetPort: 3000
  selector:
    app: tsai-deployment
