apiVersion: v1
kind: ReplicationController
metadata:
  name: tsai-replication-controller
spec:
  replicas: 3
  selector:
    app: projectscheduling
  template:
    metadata:
      labels:
        app: projectscheduling
    spec:
      containers:
      - name: my-tsai
        image: gjim/projectscheduling
        ports:
        - containerPort: 3000
